"""add graph profiles

Revision ID: 15a5aa55f3f1
Revises: 33252d9c597a
Create Date: 2026-07-11 14:10:01.421954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

INITIAL_PROFILES = [
    {
        "name": 'bordeaux',
        "is_default": True,
        "communes": [
            'Bordeaux, France',
            'Pessac, France',
            'Talence, France',
            'Mérignac, France',
            'Bègles, France',
            'Gradignan, France',
            "Villenave-d'Ornon, France",
            'Cenon, France',
            'Le Haillan, France',
            'Eysines, France',
            'Bruges, Gironde, France',
            'Le Bouscat, France',
            'Lormont, France',
            'Floirac, France',
            'Blanquefort, France',
            'Artigues-près-Bordeaux, France',
            'Ambarès-et-Lagrave, France',
            'Ambès, France',
            'Bassens, France',
            'Bouliac, France',
            'Carbon-Blanc, France',
            'Martignas-sur-Jalle, France',
            'Parempuyre, France',
            'Saint-Aubin-de-Médoc, France',
            'Saint-Louis-de-Montferrand, France',
            'Saint-Médard-en-Jalles, France',
            'Saint-Vincent-de-Paul, France',
            'Le Taillan-Médoc, France',
            'Canéjan, France',
            'Cestas, France',
            'Léognan, France',
            'Cadaujac, France',
            'La Brède, France',
            'Martillac, France',
            'Saucats, France',
            "Saint-Médard-d'Eyrans, France",
            'Saint-Selve, France',
            'Saint-Morillon, France',
            'Beautiran, France',
            'Castres-Gironde, France',
            'Ayguemorte-les-Graves, France',
            'Isle-Saint-Georges, France',
            'Cabanac-et-Villagrains, France',
        ],
    },
    {
        "name": 'bordeaux_metropole',
        "is_default": False,
        "communes": [
            'Bordeaux, France',
            'Pessac, France',
            'Talence, France',
            'Mérignac, France',
            'Bègles, France',
            'Gradignan, France',
            "Villenave-d'Ornon, France",
            'Cenon, France',
            'Le Haillan, France',
            'Eysines, France',
            'Bruges, Gironde, France',
            'Le Bouscat, France',
            'Lormont, France',
            'Floirac, France',
            'Blanquefort, France',
            'Artigues-près-Bordeaux, France',
            'Ambarès-et-Lagrave, France',
            'Ambès, France',
            'Bassens, France',
            'Bouliac, France',
            'Carbon-Blanc, France',
            'Martignas-sur-Jalle, France',
            'Parempuyre, France',
            'Saint-Aubin-de-Médoc, France',
            'Saint-Louis-de-Montferrand, France',
            'Saint-Médard-en-Jalles, France',
            'Saint-Vincent-de-Paul, France',
            'Le Taillan-Médoc, France',
        ],
    },
    {
        "name": 'victoire-campus',
        "is_default": False,
        "communes": [
            'Bordeaux, France',
            'Pessac, France',
            'Talence, France',
            'Gradignan, France',
        ],
    },
    {
        "name": 'tournai',
        "is_default": False,
        "communes": [
            'Tournai, Belgium',
            'Antoing, Belgium',
            'Leuze-en-Hainaut, Belgium',
            'Estaimpuis, Belgium',
            "Mont-de-l'Enclus, Belgium",
            'Mouscron, Belgium',
        ],
    },
]


# revision identifiers, used by Alembic.
revision: str = '15a5aa55f3f1'
down_revision: Union[str, None] = '33252d9c597a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commune_geometries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_commune_geometries_id'), 'commune_geometries', ['id'], unique=False)
    op.create_table('graph_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('communes', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('nodes', sa.Integer(), nullable=True),
    sa.Column('edges', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('built_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('built_communes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_graph_profiles_id'), 'graph_profiles', ['id'], unique=False)
    op.create_table('graph_build_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('step', sa.String(length=40), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('nodes', sa.Integer(), nullable=True),
    sa.Column('edges', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['graph_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_build_runs_id'), 'graph_build_runs', ['id'], unique=False)
    op.create_index('ix_graph_build_runs_started_at', 'graph_build_runs', ['started_at'], unique=False)
    # ### end Alembic commands ###

    _seed_initial_profiles()


def _seed_initial_profiles() -> None:
    """Crée les profils initiaux : sans eux, l'application démarrerait sans graphe."""
    profiles = sa.table(
        "graph_profiles",
        sa.column("name", sa.String),
        sa.column("communes", sa.JSON),
        sa.column("is_default", sa.Boolean),
    )
    op.bulk_insert(profiles, INITIAL_PROFILES)
    print(f"[migration] {len(INITIAL_PROFILES)} profil(s) de graphe créé(s).")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_graph_build_runs_started_at', table_name='graph_build_runs')
    op.drop_index(op.f('ix_graph_build_runs_id'), table_name='graph_build_runs')
    op.drop_table('graph_build_runs')
    op.drop_index(op.f('ix_graph_profiles_id'), table_name='graph_profiles')
    op.drop_table('graph_profiles')
    op.drop_index(op.f('ix_commune_geometries_id'), table_name='commune_geometries')
    op.drop_table('commune_geometries')
    # ### end Alembic commands ###
