"""add poi sync runs and settings

Revision ID: 33252d9c597a
Revises: e3824ec469bf
Create Date: 2026-07-11 10:45:20.318240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33252d9c597a'
down_revision: Union[str, None] = 'e3824ec469bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('total_pois', sa.Integer(), nullable=True),
    sa.Column('created_pois', sa.Integer(), nullable=True),
    sa.Column('deleted_pois', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_sync_runs_id'), 'poi_sync_runs', ['id'], unique=False)
    op.create_index('ix_poi_sync_runs_started_at', 'poi_sync_runs', ['started_at'], unique=False)
    op.create_table('poi_sync_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_sync_settings_id'), 'poi_sync_settings', ['id'], unique=False)
    # ### end Alembic commands ###

    # Ligne unique de réglages (cf. SETTINGS_ID). interval_hours NULL = synchro
    # automatique désactivée : on n'impose pas de rafraîchissement par défaut.
    op.execute("INSERT INTO poi_sync_settings (id, interval_hours) VALUES (1, NULL)")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poi_sync_settings_id'), table_name='poi_sync_settings')
    op.drop_table('poi_sync_settings')
    op.drop_index('ix_poi_sync_runs_started_at', table_name='poi_sync_runs')
    op.drop_index(op.f('ix_poi_sync_runs_id'), table_name='poi_sync_runs')
    op.drop_table('poi_sync_runs')
    # ### end Alembic commands ###
