"""add map_pois

Revision ID: e3824ec469bf
Revises: 2f7a651e33b3
Create Date: 2026-07-09 15:33:49.019735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3824ec469bf'
down_revision: Union[str, None] = '2f7a651e33b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osm_type', 'osm_id', 'category', name='uq_map_pois_osm_object_category')
    )
    op.create_index('ix_map_pois_cat_lat_lon', 'map_pois', ['category', 'latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_map_pois_id'), 'map_pois', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_pois_id'), table_name='map_pois')
    op.drop_index('ix_map_pois_cat_lat_lon', table_name='map_pois')
    op.drop_table('map_pois')
    # ### end Alembic commands ###
